### ISSUE TITLE
sharphound.ps1 erroring out on Win10 x64

### ISSUE THREAD

**Issue by gitsreerao** [BloodHoundAD/BloodHound#265] opened 2019-08-21 23:29 UTC
I downloaded the powershell script/file, and imported the module. When I try to run it within the ISE (64 or x86 version), I get this error:
```
Exception calling "Load" with "1" argument(s): "Could not load file or assembly '779776 bytes loaded from Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format."
At C:\BloodHound-win32-x64\SharpHound.ps1:512 char:2
+     $Assembly = [Reflection.Assembly]::Load($UncompressedFileBytes)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException
 
You cannot call a method on a null-valued expression.
At C:\BloodHound-win32-x64\SharpHound.ps1:515 char:2
+     $Assembly.GetType("Costura.AssemblyLoader", $false).GetMethod("At ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\BloodHound-win32-x64\SharpHound.ps1:516 char:2
+     $Assembly.GetType("Sharphound2.Sharphound").GetMethod("InvokeBloo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by rvazarkar** [comment] 2019-10-08 18:30
Closing as AV evasion is not in the scope of this project

**Closed by rvazarkar** 2019-10-08 18:30 UTC

**Comment by razzaque003** [comment] 2020-06-20 20:28
same issue for me. My antivirus and defender are turned off.


PS C:\Users\arazzaque\Desktop> Invoke-BloodHound -CollectionMethod All -Domain lab.com -ZipFilename
file.zip
Exception calling "Load" with "1" argument(s): "Could not load file or assembly '833536 bytes loade
d from System.Management.Automation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364
e35' or one of its dependencies. An attempt was made to load a program with an incorrect format."
At C:\Users\arazzaque\Desktop\SharpHound.ps1:515 char:41
+     $Assembly = [Reflection.Assembly]::Load <<<< ($UncompressedFileBytes)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

You cannot call a method on a null-valued expression.
At C:\Users\arazzaque\Desktop\SharpHound.ps1:518 char:19
+     $Assembly.GetType <<<< ("Costura.AssemblyLoader", $false).GetMethod("Attach", $BindingFlags).
Invoke($Null, @())
    + CategoryInfo          : InvalidOperation: (GetType:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\arazzaque\Desktop\SharpHound.ps1:519 char:19
+     $Assembly.GetType <<<< ("SharpHound3.SharpHound").GetMethod("InvokeSharpHound").Invoke($Null,
 @(,$passed))
    + CategoryInfo          : InvalidOperation: (GetType:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by TheWorkingDeveloper** [comment] 2022-09-07 12:37
Hey, follow up for anyone having issues with this.

This is caused by AMSI, specifically the .NET amsi. You've probably bypassed the powershell one successfully to get to this point but haven't done the .NET one.

https://s3cur3th1ssh1t.github.io/Powershell-and-the-.NET-AMSI-Interface/
The included link contains more information.
