### ISSUE TITLE
Edge filtering not working

### ISSUE THREAD

**Issue by jsdhasfedssad** [BloodHoundAD/BloodHound#619] opened 2022-11-24 14:09 UTC
The edge filtering feature in Bloodhound 4.2.0 does not work. No edges are filtered. Not even after rightclicking and selecting reload query if that is a requirement. I have tested this using the default built-in queries as well as custom queries. I expect any edge that is not checked to not be shown in the output from any queries.

I cannot find any errors in the console.

Thanks!

**Comment by rvazarkar** [comment] 2023-02-07 20:27
Can you give some steps to reproduce?

**Comment by jsdhasfedssad** [comment] 2023-02-08 07:56
Sure. Simply execute a query that results in a few objects and some edges between them. It does not matter which objects or edges you use. Then open the edge filtering menu and deselect one or all of the edges you see from the query. I do not know if the edges you deselected should now be gone or not at this time but if I assume I need to reload the query too afterwards, I get the same result. No matter what settings I used or actions I take, the filtering of edges does not happen.

**Comment by JonasBK** [comment] 2023-04-26 14:12
Hi @jsdhasfedssad,

I believe that this is not a bug but the UI not being clear enough about how the filter actually works.  
Here is an example:

First, I do a regular path search from Domain Admins to the domain object and get three edges:
![image](https://user-images.githubusercontent.com/12843299/234601022-8c93f835-17dd-4ad5-b243-5b0cbc1fa3c6.png)

Then, I remove WriteDacl in the filter:
![image](https://user-images.githubusercontent.com/12843299/234601755-87bf0078-252f-4529-9846-5bcd00d78f46.png)

Next, I run the path search again, and now the WriteDacl edge that was present before is now not shown in the result:
![image](https://user-images.githubusercontent.com/12843299/234602080-70657217-2448-450d-a96b-28ea36f3a6d0.png)

I will close this issue, but let me know if I am wrong and we should investigate this issue!

**Closed by JonasBK** 2023-04-26 14:12 UTC
Labels: bug
