### ISSUE TITLE
Unsupported OS gives false positives ?

### ISSUE THREAD

**Issue by 3isenHeiM** [BloodHoundAD/BloodHound#520] opened 2022-02-18 13:17 UTC
I'm searching for Unsupported using the [pre-built query](https://github.com/BloodHoundAD/BloodHound/blob/3e1afd96c064dbf450045624c265c9cc41c7e377/src/components/SearchContainer/Tabs/PrebuiltQueries.json#L29), and the output mentions several "Windows 10 Enterprise".

Am I missing something ? The regex doesn't include a pattern for Windows 10.

Could it be possible that it checks for the Windows 10 release (eg 21H2 etc...) to mach the unsupported ones ? I doubt since given the rule it does not appear.

![image](https://user-images.githubusercontent.com/26417172/154690148-8be0c347-2de6-410c-b99f-1d6ecefbcf2a.png)

**Comment by rvazarkar** [comment] 2022-07-18 20:16
This is pretty confusing. I cant replicate this using a regex tester, and the regex string obviously shouldn't match Windows 10. I'll have to dig a bit more into it

**Comment by rvazarkar** [comment] 2022-08-01 15:45
I've been completely unable to reproduce this on local testing. I have absolutely no idea whats going on here

**Comment by rvazarkar** [comment] 2022-08-02 20:56
Closing this until I get more info, or can repro

**Closed by rvazarkar** 2022-08-02 20:56 UTC
