### ISSUE TITLE
Incomplete JSON files in v1.0.2

### ISSUE THREAD

**Issue by anasbousselham** [BloodHoundAD/BloodHound#516] opened 2022-02-17 00:32 UTC
I have the latest ver. 4.1.0 and SharpHound v1.0.2.
The old SharpHound is not compatible, I can't upload ( file created from incompatible collector )
Do you have any idea on the issue?
Thanks

**Comment by yellow-starburst** [comment] 2022-02-17 01:15
+1 got the same error.

**Comment by yellow-starburst** [comment] 2022-02-17 14:27
Wait a minute - why is the problem ticket "Unable to connect to LDAP" but you're saying that the upload functionality doesn't work?

**Comment by rvazarkar** [comment] 2022-02-17 15:47
Can you check the meta tag at the bottom of the json files and see what the version is? There weren't any changes made to json output in v1.0.2

**Comment by anasbousselham** [comment] 2022-02-17 16:01
I have this 
```
{                                                                                                                                                                                                                                                           
  "users": [                                                                                                                                                                                                                                                
    {                                                                                                                                                                                                                                                       
      "Properties": {                                                                                                                                                                                                                                       
        "domain": "RESOURCED.LOCAL",                                                                                                                                                                                                                        
        "objectsid": "S-1-5-21-537427935-490066102-1511301751-500",                                                                                                                                                                                         
        "highvalue": false,                                                                                                                                                                                                                                 
        "enabled": true,                                                                                                                                                                                                                                    
        "lastlogon": 1645054574,                                                                                                                                                                                                                            
        "pwdlastset": 1644600080,                                                                                                                                                                                                                           
        "serviceprincipalnames": [],                                                                                                                                                                                                                        
        "hasspn": false,                                                                                                                                                                                                                                    
        "displayname": null,                                                                                                                                                                                                                                
        "email": null,                                                                                                                                                                                                                                      
        "title": null,                                                                                                                                                                                                                                      
        "homedirectory": null,                                                                                                                                                                                                                              
        "description": "Built-in account for administering the computer/domain",                                                                                                                                                                            
        "userpassword": null,                                                                                                                                                                                                                               
        "sensitive": false,                                                                                                                                                                                                                                 
        "dontreqpreauth": false,                                                                                                                                                                                                                            
        "admincount": true                                                                                                                                                                                                                                  
      },        
```

**Comment by rvazarkar** [comment] 2022-02-17 16:49
Looks like the json file didn't complete writing for some reason. Were there any exceptions when running?

**Comment by x3rz** [comment] 2022-02-19 07:06
+1
I got the same issue even when I don't provide any LDAP user credentials

**Comment by rvazarkar** [comment] 2022-02-22 17:19
If you can dm me on the BloodHound slack, I have a test binary that might fix the issue

**Comment by knrao48** [comment] 2022-02-24 12:10
RROR|Unable to connect to LDAP, verify your credentials

Although I am not providing any LDAP user credentials.

**Comment by docsewell** [comment] 2022-02-26 17:15
Right in the middle of my second OSEP attempt!  Can someone recommend a combination that doesn't have this error?  Like... fast?

**Comment by rvazarkar** [comment] 2022-02-26 17:20
You can try the binary here: https://github.com/BloodHoundAD/SharpHound/releases/tag/rolling

**Comment by x3rz** [comment] 2022-02-26 17:23
You could try Bloodhound Ingestors
Sample Command
```bash
bloodhound-python -d htb.local -u svc-alfresco@htb.local -p s3rvice -gc forest.htb.local -c all -ns 10.10.10.161 -v
```

**Comment by rtkatracy** [comment] 2022-03-25 18:28
This looks like it's still an issue with the current release of sharphound.

**Comment by rvazarkar** [comment] 2022-04-01 13:51
I've been unable to reproduce this in any of my testing, the newer version of SharpHound seems to be writing out JSON files accurately.

**Comment by mvstand** [comment] 2022-04-15 16:32
HI @rvazarkar, I do have the same issue, I am currently doing the Forest Hack the box machine, I got access with evil-winrm, and I imported the SharpHound.ps1 script that gave me a zip file which I then unzip to have the JSON files, and then I imported those json files to Bloodhound but I have the incompatible collector error, Also I tried the bloodhound-python which work when I imported the json files to bloodhound but the json files that bloodhound-python gave me it does not have the valuable info that sharp sound gave me , and the Sharphound.exe is not a valid format for evil-winrm, it has to be ps1. so I am running out of options here, my bloodhound version is 4.1.0, and sharphound.ps1 was last updated in 2020? because in the latest release like I said I only saw sharphound.exe no sharphound.ps1.

**Comment by rvazarkar** [comment] 2022-04-15 18:54
There is no SharpHound.ps1 for the newest version, so you're using an out of date collector.

**Comment by mvstand** [comment] 2022-04-15 20:13
> There is no SharpHound.ps1 for the newest version, so you're using an out of date collector

Yes, that's what I said, in that case, what would you recommend because evil-winrm does not support .exe files like Sharphound.exe latest version, It supports .ps1 that currently does not exist.  Any collector that might work with  bloodhound?

**Comment by benbasuni1** [comment] 2022-04-15 21:54
im running this
`bloodhound-python -u $user -p $pass -d $domain.local -ns $i -c All`

trying to import via json files individually and a zipped folder all together and i get this error

"file created from incompatible collector"

This was working a week ago. I have other databases in there.

**Comment by soufianetahiri** [comment] 2022-04-27 09:52
The same exact problem
![image](https://user-images.githubusercontent.com/17729335/165491944-fc461863-3110-4a74-a13f-c5e8b04739d1.png)
![image](https://user-images.githubusercontent.com/17729335/165492268-d14a99d5-0cf1-45fa-9453-6e237680e219.png)
![image](https://user-images.githubusercontent.com/17729335/165492311-8bd0fd36-87b9-4793-b3b2-869c65789561.png)

**Comment by soufianetahiri** [comment] 2022-04-27 09:57
Same problem here:
![image](https://user-images.githubusercontent.com/17729335/165493070-c0470d1f-5ff8-4668-a65e-970663c24661.png)
![image](https://user-images.githubusercontent.com/17729335/165493093-598774f2-279c-4e07-a9d6-0477b086be54.png)
![image](https://user-images.githubusercontent.com/17729335/165493109-00f997b8-812c-472d-85ba-dbd99a0ca159.png)

**Comment by docsewell** [comment] 2022-04-27 12:42
> Right in the middle of my second OSEP attempt! Can someone recommend a combination that doesn't have this error? Like... fast?

I was able to do a temporary workaround by dropping back to BH 3.0 for viewing.

**Comment by DOP7** [comment] 2022-05-07 07:21
@soufianetahiri ...I am having the same issue, i quess you are pawning blackfield from HTB because I got the same files and same NAN% error while trying to upload json files on bloodhound

**Comment by soufianetahiri** [comment] 2022-05-07 07:32
Not really it's was an actual engagement

**Comment by DOP7** [comment] 2022-05-07 14:54
@soufianetahiri ..so did u use anything else to view the json files ??...any other method?plz tell

**Comment by soufianetahiri** [comment] 2022-05-07 15:08
No.. just switched to an outdated version from an old vm sorry.

**Comment by DOP7** [comment] 2022-05-07 15:20
No issues brother..i will find this solution

**Comment by DOP7** [comment] 2022-05-08 08:20
@docsewell ...how did u view the json files in importiyin bloodhound...u said u did a workaround .?

**Comment by DOP7** [comment] 2022-05-08 09:28
got it find the solution:

Found it , I installed the BloodHound version 4.0.3  and it did import the files successfully and i can see the relationships, first degree object, everyone is facing issue with new BH realease 4.1.0

**Comment by rvazarkar** [comment] 2022-08-01 15:44
Closing this as I've been unable to reproduce this outside of the broken Kali binary

**Closed by rvazarkar** 2022-08-01 15:44 UTC

**Comment by DataWearsAHood** [comment] 2022-08-01 16:20
@rvazarkar what `broken _Kali_ binary` are you referring to? https://bloodhound.readthedocs.io/en/latest/installation/linux.html#download-the-bloodhound-gui points to the binary assets directly[, that don't seem to be distro-specific: https://github.com/BloodHoundAD/BloodHound/releases/download/4.1.0/BloodHound-linux-x64.zip??]

Has anyone seen [this issue with 4.1.1](https://github.com/BloodHoundAD/BloodHound/releases/tag/4.1.1)?

**Comment by docsewell** [comment] 2022-08-03 20:05
> ~@[rvazarkar] what `broken _Kali_ binary` are you referring to? https://bloodhound.readthedocs.io/en/latest/installation/linux.html#download-the-bloodhound-gui points to the binary assets directly[, that don't seem to be distro-specific: [releases/download/4.1.0/BloodHound-linux-x64.zip](https://github.com/BloodHoundAD/BloodHound/releases/download/4.1.0/BloodHound-linux-x64.zip)??]~ _Must be referring to `apt install bloodhound` which delivers `4.1.0-0kali` (still on 1-aug)_
> 
> Has anyone seen [this issue] with a binary from the repo? with [4.1.1](https://github.com/BloodHoundAD/BloodHound/releases/tag/4.1.1)?

Yes.

![image](https://user-images.githubusercontent.com/2394161/182698885-75e559fa-123d-43e2-b011-ce991a06da22.png)

![image](https://user-images.githubusercontent.com/2394161/182698943-206243b3-b1df-4ce0-bb9b-3f6a53c94697.png)

I noticed it says SharpHound.exe is compatible with "4.2 Release of Bloodhound", but this is what got installed with "apt install"

![image](https://user-images.githubusercontent.com/2394161/182699052-ffdd9361-9a73-43f1-ba23-765646b3b6f3.png)

**Comment by DataWearsAHood** [comment] 2022-08-04 11:41
@docsewell you got `bloodhound` from `apt`?
What do you get from `bloodhound -v` and `apt info bloodhound`?
What flavour are you using?

**Comment by docsewell** [comment] 2022-08-04 17:17
> @docsewell you got `bloodhound` from `apt`? What do you get from `bloodhound -v` and `apt info bloodhound`? What flavour are you using?

I was using the latest version of Kali.  I don't have that VM at the moment, since I destroyed it, built another, and installed BH 3.0.5 and SharpHound.exe 3.0.? just to get past the issue.

**Comment by hackcodesfree** [comment] 2022-11-17 16:55
Whats The reason

**Comment by HassanFareed** [comment] 2022-12-04 20:33
Hello,
Please check the below for the solution:

The problem of Incompatible import is related to BloodHound 4 requiring the export from SharpHound.exe instead of SharpHound.ps1 (Versions incompatibility).
You will need to run ` .\sharphound.exe` in Powershell instead. 

Check [This ](https://patrickriggs.com/blog/bloodhound-incompatible-collector/)for more details.
You can get `sharphound.exe` from the [official Github](https://github.com/BloodHoundAD/BloodHound/tree/master/Collectors).
