### ISSUE TITLE
Bloodhound crashes when running prebuilt "shortest paths to high value targets"

### ISSUE THREAD

**Issue by jackhatwick** [BloodHoundAD/BloodHound#236] opened 2019-02-28 17:01 UTC
Ive run this query on large data sets in excess of 100k objects before and 1.5 million relationships. It would take a minute but it would work. 

during processing, Bloodhound is using about 16GB of RAM out of my 32 i have allotted the VM. I have 4 cores as well and it's running 111.6% CPU on average

Now it's crashing to a white screen with the following error in the terminal running Bloodhound.
<--- Last few GCs --->

[2464:0x7db74eea000]   612058 ms: Mark-sweep 2057.7 (2129.4) -> 2056.5 (2129.4) MB, 1862.8 / 0.0 ms  (+ 52.8 ms in 13 steps since start of marking, biggest step 7.8 ms, walltime since start of marking 1918 ms) allocation failure scavenge might not succeed

<--- JS stacktrace --->
Cannot get stack trace in GC.

I have also tried using the built in query directly in neo4j but it has a syntax error.

**Comment by andyrobbins** [comment] 2019-04-16 16:27
Unfortunately this is most likely caused by our reliance on Linkurious for graph rendering, which puts all graphical rendering labor on the CPU, not the GPU. If that's the case, then unfortunately there's not a lot we can do if graphs are attempting to draw thousands of nodes. We may be able to put an option in the future to export a static graph that is not interactive, but with FOSS BloodHound we're never going to be able to render graphs with more than a few hundred nodes without serious performance impact, due to our reliance on Linkurious. The solution there would be to use a commercial graph rendering library, but those are unfortunately quite expensive and not possible to use in a free and open source project.

**Comment by rvazarkar** [comment] 2019-08-26 00:23
Closing this as wontfix since we don't have a real solution

**Closed by rvazarkar** 2019-08-26 00:23 UTC
