### ISSUE TITLE
Is there any way to host this as a web-application running in Docker?

### ISSUE THREAD

**Issue by TheKnarf** [BloodHoundAD/BloodHound#591] opened 2022-09-28 11:31 UTC
**Is your feature request related to a problem? Please describe.**
In some corporate enviroments it would be useful to host this on a server as a web application instead of as an Electron app.

**Describe the solution you'd like**
A Docker wrapper for the React app so that it can be deployed to an server.

**Describe alternatives you've considered**

**Additional context**

**Comment by jdonlonaon** [comment] 2022-11-11 14:22
For the frontend, not sure. But the neo4j backend would be pretty easy to set up in a container (docker run -p7687:7687 -p 7474:7474 neo4j).

**Comment by JonasBK** [comment] 2023-04-26 13:08
Duplicate of https://github.com/BloodHoundAD/BloodHound/issues/473

**Closed by JonasBK** 2023-04-26 13:08 UTC
Labels: duplicate, enhancement
