### ISSUE TITLE
SharpHound (v1.4) crashes/exits on Win 10 Enterprise (1709) 64-bit

### ISSUE THREAD

**Issue by jaredbarez** [BloodHoundAD/BloodHound#137] opened 2017-10-25 14:16 UTC
![image](https://user-images.githubusercontent.com/13761356/32003046-4155a17c-b99e-11e7-8d92-728d4c8af676.png)

Also, when I try to execute SharpHound.exe it crashes/exits:
![image](https://user-images.githubusercontent.com/13761356/32003400-2c953ac6-b99f-11e7-9f68-f37f770d2470.png)
![image](https://user-images.githubusercontent.com/13761356/32003547-b69e771e-b99f-11e7-9585-0838160aea30.png)

Please help.

**Comment by nerocipher** [comment] 2017-10-25 14:25
same issue Win7 Ent 64 bit

**Comment by rvazarkar** [comment] 2017-10-25 15:05
I'm actually not entirely sure how this is even possible. I'll take a look at it and see if I can find out whats causing it, but for whatever reason, the root domain object in your domain doesn't have an objectsid or its not visible to SharpHound

**Comment by jaredbarez** [comment] 2017-10-26 07:08
If it can help, PingCastle works without problem enumerating my domain and trusts (I'm not implying it uses similar methods for enumeration as SharpHound). Also, client host I'am launching SharpHound from is located behind NAT (VirtualBox VM).

**Comment by rvazarkar** [comment] 2018-03-13 02:20
Is this still an issue?

**Comment by pyrohaz4good** [comment] 2018-05-02 17:07
Bumping thread. 

This still appears to be an issue for Win10 Ent, however removing -SearchForest seems to have made it work.

**Comment by pyrohaz4good** [comment] 2018-05-02 20:39
Update, -SearchForest allows an initial enumeration but then fails after some time with a different error:

`<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Exception calling "Invoke" with "2" argument(s): "AggregateException_ctor_DefaultMessage"_x000D__x000A_</S><S S="Error">At line:436 char:2_x000D__x000A_</S><S S="Error">+     $Assembly.GetType("Sharphound2.Sharphound").GetMethod("InvokeBloo ..._x000D__x000A_</S><S S="Error">+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : AggregateException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>`

**Comment by rvazarkar** [comment] 2018-05-07 14:51
Can you run the exe version with the .pdb from here

https://github.com/BloodHoundAD/BloodHound/tree/master/Ingestors/DebugBuilds

**Comment by pyrohaz4good** [comment] 2018-05-07 16:11
Doesn't work, but we get a better error now. Ran with -s option:

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: binaryForm
   at System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(Byte[] binaryForm, Int32 offset)
   at Sharphound2.Extensions.GetSid(SearchResultEntry result) in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Extensions.cs:line 224
   at Sharphound2.Utils.GetDomainSid(String domainName) in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Utils.cs:line 663
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration() in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Enumeration\EnumerationRunner.cs:line 411
   at Sharphound2.Sharphound.Main(String[] args) in C:\Users\rvazarkar\documents\visual studio 2017\Projects\Sharphound2\Sharphound2\Sharphound.cs:line 556

**Comment by pyrohaz4good** [comment] 2018-05-07 16:25
@rvazarkar If you've got an earlier build I can try, would like to give it a go. FYI these are Windows2008R2 domains within a forest.

**Comment by rvazarkar** [comment] 2018-05-07 18:28
[SharpHound.zip](https://github.com/BloodHoundAD/BloodHound/files/1981017/SharpHound.zip)

**Comment by pyrohaz4good** [comment] 2018-05-07 18:39
Thanks but unfortunately that didn't work either. From what I can tell in the code, it can't resolve the SID of one of the domains and it crashes. (This computer is logged into Domain C, and since I specified to search the forest, it's starting at Domain A based on alphabetical order. It's crashing as soon as it tries to resolve the sid for Domain A. Enumerating Domain C seems to work for awhile but then eventually crashes with the same error). 

Interestingly enough, "Bloodhound_old.ps1" seems to be enumerating fine at the moment - it's just taking a long time. This is a very large forest I'm testing with so I'm a bit worried the posh version is going to crash at some point.

**Comment by rvazarkar** [comment] 2018-05-07 18:49
What error are you getting with this version?

**Comment by pyrohaz4good** [comment] 2018-05-07 18:54
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAdd(TKey key, TValue value)
   at Sharphound2.Cache.AddDomainFromSid(String sid, String domainName)
   at Sharphound2.Utils.GetDomainSid(String domainName)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
```

**Comment by rvazarkar** [comment] 2018-08-07 18:32
This should hopefully be fixed in 2.0. Re-open if its not!

**Closed by rvazarkar** 2018-08-07 18:32 UTC

**Comment by s-amine** [comment] 2018-12-12 09:14
`Exception lors de l'appel de « Invoke » avec « 2 » argument(s) : « AggregateException_ctor_DefaultMessage »
Au caractère C:\Users\mahafoud\Desktop\win-pwn\SharpHound.ps1:502 : 2
+     $Assembly.GetType("Sharphound2.Sharphound").GetMethod("InvokeBloo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException
`
The problem is still here

**Comment by Gwynbl31dd** [comment] 2020-01-27 10:42
I saw that bug again. Is it possible to re-open it?
