### ISSUE TITLE
Sharphound  problem, no session

### ISSUE THREAD

**Issue by orgserj** [BloodHoundAD/BloodHound#493] opened 2021-12-21 19:44 UTC
I am using the latest Sharphound, it dumped 350k objects, but not a single session =(

**Comment by rvazarkar** [comment] 2022-01-11 20:41
Is this environment on win10? If so, do you have admin rights on computers? We're making improvements in vnext that might alleviate some of this, but win10 improvements have made enumeration a lot harder

**Comment by yellow-starburst** [comment] 2022-01-13 04:39
Even if it's win10, bloodhound does indirect enumeration.
So as long as the servers aren't newer than 2016 u should get sessions.
I've had this happen to me a couple times.
Try using an older sharphoudn collector.

**Comment by Bassem-ossama** [comment] 2022-01-27 21:53
Same problem.

**Comment by yellow-starburst** [comment] 2022-02-11 04:55
Try again with new update sharphound

**Comment by rvazarkar** [comment] 2022-02-15 16:55
Closing this for now. Reopen if the problem is still there with the new sharphound

**Closed by rvazarkar** 2022-02-15 16:55 UTC

**Comment by JonasBK** [comment] 2023-04-28 12:08
Hey @ntsurisr,
Sessions are stored in the computer json:
![image](https://user-images.githubusercontent.com/12843299/235143421-f8a410e3-0544-4b7b-b446-26cc56c1e9f7.png)

**Comment by ntsurisr** [comment] 2023-04-28 12:29
Thank you @JonasBK for the quick response, haven't loaded the data into Bloodhound GUI yet, was expecting a sessions.json file. Appreciate your help.
