### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by rasta-mouse** [BloodHoundAD/BloodHound#7] opened 2016-08-08 10:20 UTC
The Powershell process consumes all available RAM on the system being run on.  In this example, it took ~1.9GB, leaving ~150MB free.

```
> Get-BloodHoundData | Export-BloodHoundCSV
```

```
> Get-Process
14995  37  1916712  1794212  2039  363.89  13100  powershell
```

**Comment by lordofthefries** [comment] 2016-08-09 13:04
I'm using a system with 32 gigs, and the process has been running for ~24 hours at this point.

**Comment by Cykhet** [comment] 2016-08-09 16:34
Also seeing this under Windows 10 64bit build (10.0.14393) - Machine specs, Intel core i7-4700HQ @ 2.40GHz, 32GB RAM

```
Exception of type 'System.OutOfMemoryException' was thrown.
At C:\Users\useraccount\Desktop\BloodHound.ps1:1596 char:17
+ ...             [Int32]$High = $Temp.GetType().InvokeMember("HighPart", [ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException
```

**Comment by Meatballs1** [comment] 2016-08-09 21:56
poke @HarmJ0y for my bastardized powerview I had to make a number of optimizations for large organisations to increase throughput and reduce memory overhead

* Reducing query count (SPEED)
* Set Get-DomainSearcher PropertiesToLoad to retrieve only the specific fields required for each result type (MEMORY/SPEED)
* Avoid PSObjects (MEMORY)
* Avoids pipelining (SPEED) - use foreach over Foreach-Object when I know there isn't going to be too many results and I wont cause too much memory usage.
* Export result ASAP (in my case straight to file) (MEMORY)
* File writes use .NET StreamWriters instead of out-file -append, this prevents AV interfering with multiple file opens (SPEED)
* Get-NetUser - stripped all the [ADSI]$MemberDN casts which cause additional queries and just retrieve $MemberDN etc. (SPEED/MEMORY)
* Make sure DomainSearcher results are disposed.

Think current large dump has been a 36Gb file. Thank goodness for lzma2 :p

**Comment by HarmJ0y** [comment] 2016-08-10 00:33
appreciate the feedback everyone (especially @Meatballs1) - taking just a day or two off after Vegas as I'm recovering and rebuilding my test domain, will try to take a look at the issue.

As far as optimizations go, some of these may take a bit of time as they would involve significant reworking of PowerView. @mattifestation and I are planning on starting a PowerSploit refactor in a month or so, so some of these major architectural optimizations may have to wait just a bit as PowerView will be mostly rewritten anyway, but I'll see this week what can be done short term.

**Comment by herrspecks** [comment] 2016-08-10 08:41
Similar issues here.
So the problem is Get-BloodHoundData related which means piping to Export-BloodHoundData will result in the same issues, right?

**Comment by vector-sec** [comment] 2016-08-10 12:58
@Meatballs1 Could you share your modifications in the interim since @HarmJ0y indicated that it may be a while before they can make some optimizations? When trying to enumerate AD groups I got to about 3MB of CSV data before Windows killed powershell for consuming too much memory.

**Comment by bkmi** [comment] 2016-08-10 15:43
Same problems here, scanning a 15,000 node network failed after 15GB of memory was consumed by powershell.exe

**Comment by vector-sec** [comment] 2016-08-10 17:58
I've got a slight workaround that I did that seems to be working so far. 

Originally I ran 

`Get-BloodHoundData -CollectionMethod Stealth | Export-BloodHoundCSV -CSVFolder "D:\bloodhound\csv"`

Which would create group_memberships.csv and eventually die due to memory utilization.

So what I did to solve this is made a slight modification to the Get-BloodHoundData function to add a GroupName parameter that is to be used in conjunction with -CollectionMethod Group

You can see the full modified script here: https://gist.github.com/vector-sec/08ea6def8fea6b8a303867926fbb589e#file-modified_bloodhound-ps1-L13397

I get setup to run things by doing the following

```
D:
cd D:\bloodhound
. .\BloodHound.ps1
Get-NetGroup | out-file groups.txt
```

From here I would compare my in progress group_memberships.csv and remove any groups from groups.txt that were completed.

Then I would pick back up where I left off by doing
```
$groups = Get-Content .\groups.txt
ForEach ($g In $groups) {
	Get-BloodHoundData -CollectionMethod Group -GroupName $g | Export-BloodHoundCSV -CSVFolder "D:\bloodhound\csv"
}
```

This method at least allows me to pick up where I left off when powershell dies due to memory utilization.

Interestingly, the original method would use all available free memory, but my workaround causes memory usage to hover around 1.2GB, on a system with 12GB this is quite nice!

**Comment by Meatballs1** [comment] 2016-08-10 18:29
@vector-sec all the modifications I made are for a seperate project, but collecting a similar dataset, so wouldn't be much use.

**Comment by HarmJ0y** [comment] 2016-08-10 20:37
Looking over the code, part of the issue as well with the Export-* functions is that they build a lookup table for all users in the global catalog where the usernames map to an array of domains they're present in. This is so we can try to deconflict where a user session originates from in a multi-domain scenario.

Obviously this saves a mapping of **username->domain** in memory for ALL users in a domain. I started trying to optimize some of this logic with https://github.com/adaptivethreat/BloodHound/commit/2819e5f34bfda3bb7cd8af43fcccfe83cb5e2146 but it will take some time to implement all of @Meatballs1's suggestions and balance the memory/time tradeoff.

**Comment by ktwombley** [comment] 2016-08-11 18:51
I included a call to `[gc]::Collect()` at the bottom of the loop in `get-netgroup`, `get-netgroupmember`, and the `ForEach($UserResult in $UserSearcher.FindAll())` loop in `get-bloodhounddata`, and at the bottom of the `process` block in `Export-BloodHoundData`. Not sure which the culprit is for sure (I suspect `get-netgroupmember`), but so far I've exported ~5k users, ~100 computers, ~500 groups, ~6k relationships into the database and i'm hovering around 250MB usage for powershell.exe.

**Comment by HarmJ0y** [comment] 2016-08-12 00:34
Currently building a test domain with 200,000 fake machines, 150,000 fake users, and 50,000 fake groups, so I should at least have a test domain to star to deal with all these scaling issues.

**Comment by derekhillhp** [comment] 2016-08-22 20:55
Any updates on this issue. Really want to scan a 50,000 user domain, but keep running out of memory.

**Comment by piffd0s** [comment] 2016-08-23 21:14
@louissanchez84 any improvement with the hp blade system?

**Comment by tenoritaiga** [comment] 2016-08-30 19:02
I made the changes @ktwombley mentioned and memory usage has built much more slowly, although it still uses quite a lot. I'm scanning a huge forest with hundreds of thousands of nodes. Get-BloodHoundData has been running for 2 days and I currently have a group_memberships.csv with about 70,000 lines, with PowerShell using about 6GB of RAM. Usage fluctuates periodically as garbage collection is done - sometimes it will drop 1GB or so and then climb back up 1.5GB. I only have 16GB to work with for this test but if it runs out again I'll try to run from a host with more available memory.

**Comment by louissanchez84** [comment] 2016-08-30 19:36
Sorry I didn't follow-up sooner. The HP Blade ran out of RAM as well.

**Comment by th3grif7er** [comment] 2016-09-06 17:54
@tenoritaiga any luck with changes @ktwombley outlined and the 16GB of RAM?

**Comment by tenoritaiga** [comment] 2016-09-06 18:26
@th3grif7er I did indeed have some measure of success with those changes. The scan ran for about 9 days before crashing this morning due to a bluescreen on the box it was running on (display driver crash, unrelated to memory consumption). It produced a group_memberships.csv of about 20MB with just under 200,000 entries, and was using only about 7.5GB of RAM. As I said before this would fluctuate up and down several GB as garbage collection was done, but this seems considerably better than without the changes. I don't currently have access to a testbed with more RAM, but am working on acquiring one. If I'm able to get on a box with 32GB or 64GB of RAM I expect a scan like this would complete successfully but take about a month to complete.

If you have a significantly smaller forest, the changes might allow you to successfully complete a scan of your environment with as little as 16GB of memory.

**Comment by henrikjohansen** [comment] 2016-09-07 06:09
I just killed a 64GB box ... the concept behind BloodHound is nice but the current PS code seems to be only for small scale deployments.

**Comment by HarmJ0y** [comment] 2016-09-08 19:31
There is now a major tuneup for the ingestor at https://github.com/adaptivethreat/BloodHound/blob/ingestor_tuneup/PowerShell/BloodHound.ps1

The goal is to try to adapt the ingestor to work on much larger sized deployments, however I don't have a 'real' large environment to test on, just the sample domain I built that has 70k+ fake groups, 100k+ fake users, and 100k+ fake computers. At least in my test environment, the new ingestor is much faster and significantly better concerning memory.

If anyone who was having previous issues wants to test, please let us know if it's an improvement or if there are lingering issues.

**Comment by vector-sec** [comment] 2016-09-08 19:54
@HarmJ0y I've started the tuned up version in our environment and it has already collected more data from AD in 15 minutes than the original release could collect in over a month. Awesome work!

**Comment by HarmJ0y** [comment] 2016-09-08 20:11
Awesome, really excited it's working significantly better! Once a few more people test we'll merge the branch into master and close this issue out.

**Comment by vector-sec** [comment] 2016-09-08 20:37
Looks like I am running into some memory issues with Session enumeration.

I tried

```Invoke-BloodHound -CollectionMethod Session -Verbose -ErrorAction Stop```

And it proceeds for a while until it runs out of memory

```VERBOSE: Computer counter: 4800```
```Exception of type 'System.OutOfMemoryException' was thrown.```

**Comment by tenoritaiga** [comment] 2016-09-08 21:02
Thank you for this. The enumeration speed is very dramatically improved, but I still do not have enough free memory to run this. It consumes about 1.5GB of RAM for every 5 minutes it runs; I haven't let it max out and crash yet but it looks like that's what it will do if I give it an hour or so. I'm going to try reapplying the garbage collection changes mentioned above on this new experimental version.

**Comment by HarmJ0y** [comment] 2016-09-09 01:53
For the group enumeration side, just did another push - https://github.com/adaptivethreat/BloodHound/commit/8c448a4aa6dfa819efbef1cbfc3b029ae68add5c

The group enumeration component should be drastically improved with memory and time. For computer enumeration, still working on how to tone down the memory consumption.

**Comment by rasta-mouse** [comment] 2016-09-09 09:02
The group enum is working nicely now.

```
> Get-BloodHoundData -CollectionMethod Group
```
```
> Get-Process
352      12    37060      43048   200     1.84  12208 powershell
```
```
09/09/2016     09:55   23712946 group_memberships.csv
```

It only took around 2 minutes to run as well :)

**Comment by derekhillhp** [comment] 2016-09-09 18:07
Ok, maybe I am a bit dense, I am trying to run the same commands as rasta-mouse and my output is displayed on the screen rather than dumped into a .csv file as indicated by harmjoy as the default. Am I missing something here. Tried the CSVFolder redirection and it is not happy.

**Comment by derekhillhp** [comment] 2016-09-12 16:08
The good news is that I have had bloodhound collecting data since last Friday and it is still going strong, with memory consumption never exceeding 2GB while I was watching on Friday and today.

It has created a group membership file with over 200k entries, the file size being just under 15MB, a local admins file with over 73k entries and the file size slightly over 5MB, a small trusts file and it now currently working on a user sessions file, which currently has about 7k entries. I guess I will let this run for several more days to see how much more content it will produce.

**Comment by lordofthefries** [comment] 2016-09-12 18:51
@derekhillhp How many threads did you set it to use?

**Comment by derekhillhp** [comment] 2016-09-12 18:57
@lordofthefries - just using the default settings as provided in the new branch. Just running this:

 Get-BloodHoundData | Export-BloodHoundCSV

**Comment by HarmJ0y** [comment] 2016-09-13 05:43
So the new [branch no longer has Export-BloodHoundCSV](https://github.com/adaptivethreat/BloodHound/blob/ingestor_tuneup/PowerShell/BloodHound.ps1), so if that command is what's running then you have the old version loaded in some way. The Export-* cmdlets have been combined with Get-BloodHoundData into just **Invoke-BloodHound**. If the old version is indeed running but memory consumption hasn't spiked, then you get why trying to debug this has been maddening :)

@lordofthefries - **Invoke-BloodHound** is now threaded by default with 20.

**Comment by derekhillhp** [comment] 2016-09-13 15:44
Now that is interesting. I cloned the branch to a separate directory and even rebooted the computer to ensure that none of the other modules were left in memory. I then imported the new bloodhound and ran the commands, as a matter of fact, the new command didn't work, hence I had to revert to the old command. What is strange is if I am indeed running the old version, why have I not run out of memory, before it took about 4-6 hours, I am now going on 96 hours and it is still going using less than 2GB of RAM. If I abort now, remove the old bloodhound files and re-run this, can I just run the sessiosn or is that not even needed by using the global catalog.

**Comment by tenoritaiga** [comment] 2016-09-13 18:13
I let the newest revision run last night; looks like it ran for about 2.5 hours before running out of memory. The backlog shows hundreds of lines like this:

`VERBOSE: Error ending Invoke-BloodHound thread 11397 : Exception calling "EndInvoke" with "1" argument(s): "Exception of type 'System.OutOfMemoryException' was thrown."`

The collection speed is dramatically better, though. In those 2.5 hours it generated a group_memberships.csv of 1.3GB with about 13 million entries. If the memory usage can be further improved or if I can source a box with more RAM I'm sure I can complete the scan. Thanks for the work on this.

**Comment by derekhillhp** [comment] 2016-09-14 15:02
So it completed, yeah, but I am getting quite a few errors, not sure if these mean that the data is incomplete or if they can be ignored.

VERBOSE: Error ending Invoke-BloodHound thread 104539 : Exception calling "EndInvoke" with "1" argument(s): "An error occurred while creating the pipeline."

**Comment by rvazarkar** [comment] 2016-10-03 02:23
So @HarmJ0y pushed some changes to the ingestor_tuneup branch over the weekend that might solve a lot of these issues. We would love some feedback from people who can test this to see if its been resolved.

https://github.com/adaptivethreat/BloodHound/blob/ingestor_tuneup/PowerShell/BloodHound.ps1

**Comment by rasta-mouse** [comment] 2016-10-06 08:18
So this is where I am on the latest ingestor_tuneup branch.

![bloodhound](https://cloud.githubusercontent.com/assets/7346521/19145107/3a5aa250-8ba5-11e6-80e7-75ec75d08ab0.PNG)

The process is consuming ~155MB of RAM, but it doesn't progress from here.  I waited around 6 hours before killing it.  `group_membership.csv` is ~23MB and contains ~30k lines.

**Comment by qgrosperrin** [comment] 2016-11-06 19:26
@HarmJ0y any chance you'd share the script (assuming that's the case) you used to generate your fake AD domain mentioned in https://github.com/adaptivethreat/BloodHound/issues/7#issuecomment-245713020 ? It'd be quite handy for QA testing. Cheers

**Comment by ashr** [comment] 2016-11-09 12:34
Thought I left a comment, but it ain't here. The tuneup made the difference between working and not working for me, thank you very much. Memory usage went down from 3GB+ to ~500MB and result was achieved in less than 6 hours. group_membership.csv ended up being 52megs.

**Comment by craigsmooth** [comment] 2016-11-10 01:28
Any idea why the improved ingestor would leave the local admins csv with no entries? Everything else seems to work fine and it completed in a reasonable amount of time. Thank you

**Comment by louissanchez** [comment] 2016-12-02 20:29
I tried the new ingestor and it works well. I'm still testing, but it actually completed which is great.

**Comment by ad0nis** [comment] 2016-12-07 16:46
The new ingestor script allowed me to map a very large domain today which previously threw OOM errors. Any idea when this will be merged in, so we don't have to pull the optimized script separately?

**Comment by shell-c0d3** [comment] 2017-01-06 09:19
Thanks, update fixed problem for me when running a 100000+ user domain.

**Comment by rvazarkar** [comment] 2017-03-28 00:56
Closing this since it looks like everything is working nicely. There'll be more improvements to the ingestor in the (near) future as well.

**Closed by rvazarkar** 2017-03-28 00:56 UTC
